load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_binary", "go_test")

# Buildpack for the Node.js runtime.
load("//tools:defs.bzl", "buildpack")

licenses(["notice"])

buildpack(
    name = "sdk",
    executables = [
        ":main",
    ],
    prefix = "flutter",
    version = "1.0.0",
    visibility = [
        "//builders:flutter_builders",
    ],
)

go_library(
    name = "main_lib",
    srcs = [
        "main.go",
    ],
    importpath = "github.com/GoogleCloudPlatform/buildpacks/" + package_name(),
    visibility = [
        "//:__subpackages__",
    ],
    deps = [
        "//pkg/flutter",
        "//pkg/gcpbuildpack",
        "//pkg/runtime",
    ],
)

go_binary(
    name = "main",
    # Strip debugging information to reduce binary size.
    gc_linkopts = [
        "-s",
        "-w",
    ],
    embed = [":main_lib"],
)

go_test(
    name = "main_test",
    size = "small",
    srcs = ["main_test.go"],
    embed = [":main_lib"],
    rundir = ".",
    deps = [
        "//internal/buildpacktest",
    ],
)
